"""
scaffold.py — Generate a SKILL.md stub pre-filled with the project's detected stack.

Command: agent-hunter scaffold <name>

Also triggered automatically by the hunt pipeline when:
    - Hunt returns 0 results (nothing found for your stack)
    - User explicitly asks to create a new skill

Uses assets/skill_stub_template.md as the base template.
Fills in detected tech stack signals from context_extractor.py.

Output: A new SKILL.md file ready for the user to customize.

No LLM calls. No network access.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from context_extractor import ContextProfile, extract_context


TEMPLATE_PATH = Path(__file__).parent.parent / "assets" / "skill_stub_template.md"


def scaffold_skill(
    name: str,
    output_path: Optional[Path] = None,
    profile: Optional[ContextProfile] = None,
    project_root: str = ".",
    author: str = "",
) -> Path:
    """Generate a SKILL.md stub for a new skill.

    Args:
        name: Name of the skill (e.g. "my-fastapi-helper").
        output_path: Where to write the stub. Defaults to ./<name>/SKILL.md
        profile: Pre-existing ContextProfile. If None, extracts from project_root.
        project_root: Used to extract context if profile is not provided.
        author: Author name/handle for the frontmatter.

    Returns:
        Path to the generated stub file.
    """
    if profile is None:
        print(f"[agent-hunter] Extracting project context from: {project_root}")
        profile = extract_context(project_root)

    template = _load_template()
    stub = _fill_template(template, name=name, profile=profile, author=author)

    if output_path is None:
        output_path = Path(project_root) / name / "SKILL.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(stub, encoding="utf-8")

    print(f"\n✅ Scaffold created: {output_path}")
    print("\nNext steps:")
    print(f"  1. Open {output_path} and replace all {{{{placeholders}}}}")
    print("  2. Test your trigger phrases in a Claude session")
    print("  3. Run `agent-hunter audit` after installing to check for conflicts")
    print("  4. Share it: open a PR to add it to references/VERIFIED_SKILLS.md")

    return output_path


def _load_template() -> str:
    """Load the skill stub template."""
    if not TEMPLATE_PATH.exists():
        # Fallback minimal template if assets file is missing
        return MINIMAL_TEMPLATE
    return TEMPLATE_PATH.read_text(encoding="utf-8")


def _fill_template(template: str, name: str, profile: ContextProfile, author: str) -> str:
    """Fill template placeholders with real values."""
    stack_str = ", ".join(profile.tech_stack[:8]) if profile.tech_stack else "your stack"
    domain_str = ", ".join(profile.domain_tags[:4]) if profile.domain_tags else "general"

    replacements = {
        "{{skill_name}}": _slugify(name),
        "{{skill_description}}": f"A {domain_str} skill for {stack_str} projects.",
        "{{author}}": author or "your-github-handle",
        "{{date}}": datetime.now().strftime("%Y-%m-%d"),
        "{{detected_stack}}": stack_str,
        "{{primary_trigger}}": f"help me with {name.replace('-', ' ')}",
    }

    result = template
    for placeholder, value in replacements.items():
        result = result.replace(placeholder, value)

    return result


def _slugify(name: str) -> str:
    """Convert name to kebab-case slug."""
    name = name.lower().strip()
    name = re.sub(r'[^\w\s-]', '', name)
    name = re.sub(r'[\s_]+', '-', name)
    return name.strip('-')


# Minimal fallback template if assets/skill_stub_template.md is missing
MINIMAL_TEMPLATE = """\
---
name: "{{skill_name}}"
description: "{{skill_description}}"
version: "0.1.0"
license: "MIT"
author: "{{author}}"
compatibility:
  claude: ">=1.0.0"
triggers:
  - "{{primary_trigger}}"
mcp_dependencies: []
---

# {{skill_name}}

<!-- Generated by agent-hunter scaffold on {{date}} -->
<!-- Stack detected: {{detected_stack}} -->

## What This Skill Does

{{skill_description}}

## Instructions

1. Understand what the user needs.
2. [Add your steps here]

## Examples

**User:** {{primary_trigger}}
**Response:** [Describe expected response]
"""


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Scaffold a new SKILL.md stub")
    parser.add_argument("name", help="Name for the new skill (e.g. my-fastapi-helper)")
    parser.add_argument("--output", "-o", help="Output path for SKILL.md", default=None)
    parser.add_argument("--project", "-p", help="Project root for context extraction", default=".")
    parser.add_argument("--author", "-a", help="Author name/handle", default="")
    args = parser.parse_args()

    output = Path(args.output) if args.output else None
    scaffold_skill(
        name=args.name,
        output_path=output,
        project_root=args.project,
        author=args.author,
    )
